// Script de migration para criar tabela faturas_cartao, trigger e migrar dados históricos
// Padrão: mesmo que apply-functions.js (CommonJS + pg + db direto)
// Uso: node supabase/migration-faturas.js

const { Client } = require('pg');

const PROD_URL = 'postgresql://postgres:Srbr19010720%40@db.vhuvnutzklhskkwbpxdz.supabase.co:5432/postgres';
const SSL = { rejectUnauthorized: false };

async function main() {
    const db = new Client({ connectionString: decodeURIComponent(PROD_URL), ssl: SSL });
    await db.connect();
    console.log('✅ Conectado ao banco!\n');

    const passos = [
        {
            nome: 'PASSO 1 — Criar tabela faturas_cartao',
            sql: `
CREATE TABLE IF NOT EXISTS public.faturas_cartao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id bigint NOT NULL REFERENCES public.contas_financeiras(id) ON DELETE CASCADE,
    mes_referencia text NOT NULL,
    data_vencimento date NOT NULL,
    status text NOT NULL DEFAULT 'Aberta',
    organizacao_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_fatura_conta_mes UNIQUE(conta_id, mes_referencia)
);
ALTER TABLE public.faturas_cartao ENABLE ROW LEVEL SECURITY;`
        },
        {
            nome: 'PASSO 2 — Adicionar coluna fatura_id em lancamentos',
            sql: `ALTER TABLE public.lancamentos ADD COLUMN IF NOT EXISTS fatura_id bigint REFERENCES public.faturas_cartao(id) ON DELETE SET NULL;`
        },
        {
            nome: 'PASSO 3 — Criar função trigger fn_vincular_lancamento_fatura',
            sql: `
CREATE OR REPLACE FUNCTION public.fn_vincular_lancamento_fatura()
RETURNS trigger AS $$
DECLARE
    v_conta_id bigint;
    v_tipo_conta text;
    v_dia_fechamento integer;
    v_dia_pagamento integer;
    v_mes_referencia text;
    v_data_vencimento date;
    v_fatura_id bigint;
    v_data_comp date;
BEGIN
    -- A tabela lancamentos usa "conta_id" (uma coluna só para qualquer tipo)
    v_conta_id := NEW.conta_id;

    IF v_conta_id IS NULL THEN RETURN NEW; END IF;

    SELECT tipo, dia_fechamento_fatura, dia_pagamento_fatura
    INTO v_tipo_conta, v_dia_fechamento, v_dia_pagamento
    FROM public.contas_financeiras WHERE id = v_conta_id;

    IF v_tipo_conta IS DISTINCT FROM 'Cartão de Crédito' THEN
        NEW.fatura_id := NULL;
        RETURN NEW;
    END IF;

    IF v_dia_fechamento IS NULL OR v_dia_pagamento IS NULL OR NEW.data_transacao IS NULL THEN
        RETURN NEW;
    END IF;

    v_data_comp := NEW.data_transacao;

    -- Antes do fechamento = fatura do mês corrente; no dia ou depois = mês seguinte
    IF EXTRACT(DAY FROM v_data_comp) >= v_dia_fechamento THEN
        v_data_comp := v_data_comp + INTERVAL '1 month';
    END IF;
    v_mes_referencia := to_char(v_data_comp, 'YYYY-MM');

    -- Calcular data de vencimento exata
    IF v_dia_pagamento <= v_dia_fechamento THEN
        v_data_vencimento := (to_char(v_data_comp + INTERVAL '1 month', 'YYYY-MM-') || LPAD(v_dia_pagamento::text, 2, '0'))::date;
    ELSE
        v_data_vencimento := (v_mes_referencia || '-' || LPAD(v_dia_pagamento::text, 2, '0'))::date;
    END IF;

    -- Sobrescrever data_vencimento com o valor oficial calculado
    NEW.data_vencimento := v_data_vencimento;

    -- Buscar ou criar a fatura
    SELECT id INTO v_fatura_id FROM public.faturas_cartao
    WHERE conta_id = v_conta_id AND mes_referencia = v_mes_referencia;

    IF v_fatura_id IS NULL THEN
        INSERT INTO public.faturas_cartao (conta_id, mes_referencia, data_vencimento, organizacao_id)
        VALUES (v_conta_id, v_mes_referencia, v_data_vencimento, NEW.organizacao_id)
        RETURNING id INTO v_fatura_id;
    END IF;

    NEW.fatura_id := v_fatura_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;`
        },
        {
            nome: 'PASSO 4 — Criar trigger na tabela lancamentos',
            sql: `
DROP TRIGGER IF EXISTS trg_vincular_fatura_lancamento ON public.lancamentos;
CREATE TRIGGER trg_vincular_fatura_lancamento
BEFORE INSERT OR UPDATE ON public.lancamentos
FOR EACH ROW EXECUTE FUNCTION public.fn_vincular_lancamento_fatura();`
        },
        {
            nome: 'PASSO 5 — Migração histórica (vincular lançamentos de cartão existentes)',
            sql: `
DO $$
DECLARE
    rec RECORD;
    v_dia_fechamento integer;
    v_dia_pagamento integer;
    v_data_comp date;
    v_mes_referencia text;
    v_data_vencimento date;
    v_fatura_id bigint;
    total_migrados integer := 0;
BEGIN
    FOR rec IN
        SELECT l.id, l.data_transacao, l.organizacao_id, l.conta_id
        FROM public.lancamentos l
        JOIN public.contas_financeiras c ON c.id = l.conta_id
        WHERE c.tipo = 'Cartão de Crédito'
          AND l.fatura_id IS NULL
          AND l.data_transacao IS NOT NULL
    LOOP
        SELECT dia_fechamento_fatura, dia_pagamento_fatura
        INTO v_dia_fechamento, v_dia_pagamento
        FROM public.contas_financeiras WHERE id = rec.conta_id;

        IF v_dia_fechamento IS NULL OR v_dia_pagamento IS NULL THEN CONTINUE; END IF;

        v_data_comp := rec.data_transacao;
        IF EXTRACT(DAY FROM v_data_comp) >= v_dia_fechamento THEN
            v_data_comp := v_data_comp + INTERVAL '1 month';
        END IF;
        v_mes_referencia := to_char(v_data_comp, 'YYYY-MM');

        IF v_dia_pagamento <= v_dia_fechamento THEN
            v_data_vencimento := (to_char(v_data_comp + INTERVAL '1 month', 'YYYY-MM-') || LPAD(v_dia_pagamento::text, 2, '0'))::date;
        ELSE
            v_data_vencimento := (v_mes_referencia || '-' || LPAD(v_dia_pagamento::text, 2, '0'))::date;
        END IF;

        SELECT id INTO v_fatura_id FROM public.faturas_cartao
        WHERE conta_id = rec.conta_id AND mes_referencia = v_mes_referencia;

        IF v_fatura_id IS NULL THEN
            INSERT INTO public.faturas_cartao (conta_id, mes_referencia, data_vencimento, organizacao_id)
            VALUES (rec.conta_id, v_mes_referencia, v_data_vencimento, rec.organizacao_id)
            RETURNING id INTO v_fatura_id;
        END IF;

        UPDATE public.lancamentos SET fatura_id = v_fatura_id WHERE id = rec.id;
        total_migrados := total_migrados + 1;
    END LOOP;
    RAISE NOTICE 'Migrados % lançamentos históricos.', total_migrados;
END;
$$;`
        }
    ];

    for (const { nome, sql } of passos) {
        try {
            process.stdout.write(`⏳ ${nome}... `);
            await db.query(sql);
            console.log('✅ OK!');
        } catch (err) {
            console.log(`❌ Erro: ${err.message.slice(0, 120)}`);
        }
    }

    // Resultado final
    console.log('\n📊 RESULTADO FINAL:');
    const resultado = await db.query(`
        SELECT 
            cf.nome AS cartao,
            fc.mes_referencia,
            fc.data_vencimento,
            fc.status,
            COUNT(l.id) AS lancamentos,
            COALESCE(SUM(CASE WHEN l.tipo='Despesa' THEN l.valor ELSE 0 END),0) AS total_despesas
        FROM public.faturas_cartao fc
        JOIN public.contas_financeiras cf ON cf.id = fc.conta_id
        LEFT JOIN public.lancamentos l ON l.fatura_id = fc.id
        GROUP BY cf.nome, fc.id, fc.mes_referencia, fc.data_vencimento, fc.status
        ORDER BY fc.mes_referencia DESC LIMIT 20;
    `);
    console.table(resultado.rows);

    const semFatura = await db.query(`
        SELECT COUNT(*) AS sem_fatura
        FROM public.lancamentos l
        JOIN public.contas_financeiras c ON c.id = l.conta_id
        WHERE c.tipo = 'Cartão de Crédito' AND l.fatura_id IS NULL;
    `);
    console.log(`\n⚠️  Lançamentos de cartão AINDA sem fatura: ${semFatura.rows[0].sem_fatura}`);

    await db.end();
    console.log('\n🔌 Concluído!');
}

main().catch(err => console.error('❌ FATAL:', err.message));
