-- 1. Cria a Tabela Individual para Preferências de Tela do Usuário
CREATE TABLE IF NOT EXISTS public.sys_user_notification_prefs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    template_id bigint NOT NULL REFERENCES public.sys_notification_templates(id) ON DELETE CASCADE,
    canal_sistema boolean NOT NULL DEFAULT true,
    canal_push boolean NOT NULL DEFAULT true,
    organizacao_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE(usuario_id, template_id)
);

-- Ativa RLS para Segurança
ALTER TABLE public.sys_user_notification_prefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuários veem suas próprias prefs" 
    ON public.sys_user_notification_prefs FOR SELECT 
    USING (auth.uid() = usuario_id);

CREATE POLICY "Usuários atualizam suas próprias prefs" 
    ON public.sys_user_notification_prefs FOR INSERT 
    WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Usuários modificam suas próprias prefs" 
    ON public.sys_user_notification_prefs FOR UPDATE 
    USING (auth.uid() = usuario_id);

-- 2. Cria a RPC cruzando Cargos x Configuração do Proprietário
-- Esta função retorna as notificações que o usuário tem acesso baseado em seu Cargo
CREATE OR REPLACE FUNCTION public.get_user_allowed_notifications(p_user_id uuid, p_organizacao_id bigint)
 RETURNS TABLE(
    id bigint,
    nome_regra text,
    tabela_alvo text,
    evento text,
    icone text,
    enviar_push boolean
 )
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_cargo_id bigint;
BEGIN
    -- 1. Encontra o cargo_id do usuário logado através do Vínculo de Funcionário
    SELECT f.cargo_id INTO v_cargo_id
    FROM public.usuarios u
    JOIN public.funcionarios f ON u.funcionario_id = f.id
    WHERE u.id = p_user_id
    AND u.is_active = true
    LIMIT 1;

    -- 2. Retorna a lista mestre (Templates) Cruzada com as Permissões (Settings)
    RETURN QUERY
    SELECT 
        t.id,
        t.nome_regra,
        t.tabela_alvo,
        t.evento,
        t.icone,
        s.enviar_push
    FROM public.sys_notification_templates t
    JOIN public.sys_org_notification_settings s 
        ON t.id = s.template_id
    WHERE s.organizacao_id = p_organizacao_id
      AND s.is_active = true
      -- A mágica do Array: Verifica se o cargo do cara está no Array de ids que o admin liberou.
      -- Se a conta dele não tiver cargo, ele não vê nada. Se a flag for nula, assume false.
      AND (
        v_cargo_id IS NOT NULL 
        AND v_cargo_id = ANY(s.funcoes_ids)
      );
END;
$function$;
