-- SCRIPT DE CRIAÇÃO E AUTOMAÇÃO: FATURAS DE CARTÃO DE CRÉDITO
-- Este script estruturará o agrupamento direto no Banco de Dados.

-- 1. Criação da Tabela faturas_cartao
CREATE TABLE IF NOT EXISTS public.faturas_cartao (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id bigint NOT NULL REFERENCES public.contas_financeiras(id) ON DELETE CASCADE,
    mes_referencia text NOT NULL, -- Ex: '2026-03'
    data_vencimento date NOT NULL, -- Data exata calculada para pagamento
    status text NOT NULL DEFAULT 'Aberta', -- Aberta, Paga, Atrasada, etc.
    organizacao_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    total_despesas numeric DEFAULT 0,
    total_pago numeric DEFAULT 0,
    UNIQUE(conta_id, mes_referencia) -- Uma conta só pode ter 1 fatura por mês de referência
);

-- Habilitar RLS
ALTER TABLE public.faturas_cartao ENABLE ROW LEVEL SECURITY;

-- 2. Adicionar fatura_id na tabela lancamentos (caso não exista)
ALTER TABLE public.lancamentos ADD COLUMN IF NOT EXISTS fatura_id bigint REFERENCES public.faturas_cartao(id) ON DELETE SET NULL;

-- 3. Função Autônoma (Trigger) para calcular e vincular a Fatura ANTES de inserir/atualizar um Lançamento
CREATE OR REPLACE FUNCTION public.fn_vincular_lancamento_fatura()
RETURNS trigger AS $$
DECLARE
    v_conta_id bigint;
    v_tipo_conta text;
    v_dia_fechamento integer;
    v_dia_pagamento integer;
    v_mes_referencia text;
    v_data_vencimento date;
    v_fatura_id bigint;
    v_data_base date;
BEGIN
    -- Determinar se é Despesa (conta_origem) ou Receita/Estorno (conta_destino) no Cartão
    IF NEW.tipo IN ('Despesa', 'Receita') THEN
        IF NEW.tipo = 'Despesa' THEN
            v_conta_id := NEW.conta_origem_id;
        ELSIF NEW.tipo = 'Receita' THEN
            v_conta_id := NEW.conta_destino_id;
        END IF;

        IF v_conta_id IS NOT NULL THEN
            -- Buscar informações da conta (se é Cartão de Crédito e dias)
            SELECT tipo, dia_fechamento_fatura, dia_pagamento_fatura 
            INTO v_tipo_conta, v_dia_fechamento, v_dia_pagamento
            FROM public.contas_financeiras 
            WHERE id = v_conta_id;

            IF v_tipo_conta = 'Cartão de Crédito' THEN
                
                -- Se não houver dia fechamento ou pagamento configurado, ignorar (sair)
                IF v_dia_fechamento IS NULL OR v_dia_pagamento IS NULL THEN
                    RETURN NEW;
                END IF;

                v_data_base := NEW.data_transacao;

                -- CALCULAR O MÊS DE REFERÊNCIA DA FATURA:
                -- Se a transação foi antes do dia de fechamento, cai na fatura do mês atual da transação.
                -- Se a transação foi no dia ou após o fechamento, cai na fatura do mês SEGUINTE.
                IF EXTRACT(DAY FROM v_data_base) >= v_dia_fechamento THEN
                    v_data_base := v_data_base + INTERVAL '1 month';
                END IF;

                -- Montar mes_referencia (YYYY-MM)
                v_mes_referencia := to_char(v_data_base, 'YYYY-MM');

                -- Calcular data de vencimento exata
                -- ATENÇÃO: Se o pagamento é "Menor" que o fechamento, o pagamento é no mês seguinte ao fechamento.
                -- Ex: Fechamento 28, Pagamento 10 (do mês seguinte).
                IF v_dia_pagamento <= v_dia_fechamento THEN
                   -- Para um fechamento 28, a fatura de Março (mês_referencia 03) terá pagamento em 10/04
                   -- Entao a data de vencimento será montada com base no mês seguinte a v_data_base
                   v_data_vencimento := (to_char(v_data_base + INTERVAL '1 month', 'YYYY-MM-') || LPAD(v_dia_pagamento::text, 2, '0'))::date;
                ELSE
                   -- Se pagamento for maior, exemplo: Fechamento 05, Pagamento 15. A fatura de Março (03) é paga em 15/03.
                   v_data_vencimento := (v_mes_referencia || '-' || LPAD(v_dia_pagamento::text, 2, '0'))::date;
                END IF;

                -- Override de seguranca da data_vencimento no lançamento
                NEW.data_vencimento := v_data_vencimento;

                -- BUSCAR OU CRIAR A FATURA
                SELECT id INTO v_fatura_id 
                FROM public.faturas_cartao 
                WHERE conta_id = v_conta_id AND mes_referencia = v_mes_referencia;

                IF v_fatura_id IS NULL THEN
                    -- Se não existe, cria a fatura e já retorna o ID
                    INSERT INTO public.faturas_cartao (conta_id, mes_referencia, data_vencimento, organizacao_id)
                    VALUES (v_conta_id, v_mes_referencia, v_data_vencimento, NEW.organizacao_id)
                    RETURNING id INTO v_fatura_id;
                END IF;

                -- Amarrar o lançamento à fatura
                NEW.fatura_id := v_fatura_id;
            ELSE
                -- Se não é cartão de crédito, garantir que fatura_id seja nulo
                NEW.fatura_id := NULL;
            END IF;
        END IF;

    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Associar a Trigger à tabela lancamentos
DROP TRIGGER IF EXISTS trg_vincular_fatura_lancamento ON public.lancamentos;

CREATE TRIGGER trg_vincular_fatura_lancamento
BEFORE INSERT OR UPDATE ON public.lancamentos
FOR EACH ROW
EXECUTE FUNCTION public.fn_vincular_lancamento_fatura();
